const BASE_TABS = [
  "Today",
  "Scheduler",
  "Notes",
  "New Request",
  "Open Requests",
  "Request History",
  "Pull Paper Request",
  "Supplies Request",
  "Daily Shipment",
  "Shipment Emails",
  "Activity Log",
];

export const DEMO_DEFAULT_USERNAME = "Admin";
export const DEMO_DEFAULT_PASSWORD = "demo123";

function startOfWeek(input) {
  const date = new Date(input);
  const day = date.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  date.setDate(date.getDate() + diff);
  date.setHours(0, 0, 0, 0);
  return date;
}

function addDays(date, days) {
  const copy = new Date(date);
  copy.setDate(copy.getDate() + days);
  return copy;
}

function isoDate(date) {
  if (!date) return "";
  const year = date.getFullYear();
  const month = String(date.getMonth() + 1).padStart(2, "0");
  const day = String(date.getDate()).padStart(2, "0");
  return `${year}-${month}-${day}`;
}

function atTime(date, hours, minutes = 0) {
  return new Date(date.getFullYear(), date.getMonth(), date.getDate(), hours, minutes, 0, 0).toISOString();
}

function makeJob({
  number,
  customerName,
  generalDescr,
  press,
  priority,
  quantity,
  footage,
  pressTime,
  stock,
  shipByDate,
  dueOnSiteDate,
  status = "Open",
  dateDone = null,
  custPoNum = "",
  mainTool = "",
  toolNo2 = "",
  notes = "",
  holdActive = false,
  holdNote = "",
}) {
  return {
    id: String(number),
    press,
    number: String(number),
    customerName,
    generalDescr,
    custPoNum,
    priority,
    shipByDate,
    entryDate: addDays(shipByDate, -7),
    dueOnSiteDate,
    stockNum2: stock,
    stockNum1: "",
    stockDisplay: stock,
    ticketStatus: status,
    normalizedStatus: String(status).toLowerCase() === "done" ? "closed" : "open",
    mainTool,
    toolNo2,
    ticQuantity: quantity,
    estFootage: footage,
    estPressTime: pressTime,
    notes,
    dateDone,
    holdActive,
    holdNote,
    raw: {},
  };
}

export function buildDemoSharedSnapshot(now = new Date()) {
  const weekStart = startOfWeek(now);
  const monday = addDays(weekStart, 0);
  const tuesday = addDays(weekStart, 1);
  const wednesday = addDays(weekStart, 2);
  const thursday = addDays(weekStart, 3);
  const friday = addDays(weekStart, 4);
  const todayKey = isoDate(now);

  const jobs = [
    makeJob({
      number: 21041,
      customerName: "Blue Ridge Foods",
      generalDescr: '4" x 6" Breakfast Blend label',
      press: "5.1",
      priority: "High",
      quantity: 182000,
      footage: 22450,
      pressTime: 5.3,
      stock: "585",
      shipByDate: thursday,
      dueOnSiteDate: friday,
      custPoNum: "PO-784510",
      mainTool: "421",
      toolNo2: "D-117",
    }),
    makeJob({
      number: 21042,
      customerName: "Northshore Organics",
      generalDescr: '3.25" x 4.5" Citrus tea front',
      press: "6.1",
      priority: "Release",
      quantity: 94000,
      footage: 11120,
      pressTime: 3.6,
      stock: "266",
      shipByDate: friday,
      dueOnSiteDate: friday,
      custPoNum: "PO-118204",
      mainTool: "618",
      toolNo2: "D-204",
    }),
    makeJob({
      number: 21043,
      customerName: "Summit Pet Co.",
      generalDescr: '2.75" x 5.5" Chicken recipe side panel',
      press: "1.1",
      priority: "Inventory",
      quantity: 56000,
      footage: 7850,
      pressTime: 2.7,
      stock: "824",
      shipByDate: thursday,
      dueOnSiteDate: friday,
      custPoNum: "PO-771002",
      mainTool: "266",
      toolNo2: "D-305",
    }),
    makeJob({
      number: 21044,
      customerName: "Harbor Snacks",
      generalDescr: '5" x 7" Family size bag front',
      press: "2.1",
      priority: "Open",
      quantity: 240000,
      footage: 30100,
      pressTime: 7.8,
      stock: "585",
      shipByDate: friday,
      dueOnSiteDate: friday,
      custPoNum: "PO-664220",
      mainTool: "585",
      toolNo2: "D-089",
      holdActive: true,
      holdNote: "Waiting on revised flavor callout approval.",
    }),
    makeJob({
      number: 21045,
      customerName: "Grove & Grain",
      generalDescr: '4.5" x 3.25" Granola cup digital batch',
      press: "8",
      priority: "Digital",
      quantity: 12000,
      footage: 1950,
      pressTime: 0.9,
      stock: "Digital gloss",
      shipByDate: friday,
      dueOnSiteDate: friday,
      custPoNum: "PO-551204",
      mainTool: "DIG-44",
      toolNo2: "",
    }),
    makeJob({
      number: 21046,
      customerName: "Cedar Valley Coffee",
      generalDescr: '3" x 5.25" Espresso roast release',
      press: "5.1",
      priority: "Release",
      quantity: 88000,
      footage: 9540,
      pressTime: 2.8,
      stock: "266",
      shipByDate: thursday,
      dueOnSiteDate: thursday,
      status: "Done",
      dateDone: thursday,
      custPoNum: "PO-401225",
      mainTool: "266",
      toolNo2: "D-611",
    }),
    makeJob({
      number: 21047,
      customerName: "Maple Street Tea",
      generalDescr: '4.125" x 3.125" Variety pack panel',
      press: "6.1",
      priority: "Release",
      quantity: 134000,
      footage: 14840,
      pressTime: 4.1,
      stock: "585",
      shipByDate: thursday,
      dueOnSiteDate: thursday,
      status: "Done",
      dateDone: thursday,
      custPoNum: "PO-902144",
      mainTool: "585",
      toolNo2: "D-144",
    }),
    makeJob({
      number: 21048,
      customerName: "Peak Pantry",
      generalDescr: '3.5" x 4.75" Protein blend contract release',
      press: "8",
      priority: "Release",
      quantity: 26000,
      footage: 3120,
      pressTime: 1.1,
      stock: "266",
      shipByDate: friday,
      dueOnSiteDate: friday,
      status: "Done",
      dateDone: friday,
      custPoNum: "PO-882341",
      mainTool: "266",
      toolNo2: "D-512",
    }),
    makeJob({
      number: 21049,
      customerName: "Evergreen Market",
      generalDescr: '2.5" x 6.0" cold brew wrap',
      press: "9",
      priority: "Open",
      quantity: 41000,
      footage: 5250,
      pressTime: 1.7,
      stock: "825",
      shipByDate: friday,
      dueOnSiteDate: friday,
      custPoNum: "PO-772110",
      mainTool: "825",
      toolNo2: "D-010",
    }),
    makeJob({
      number: 21050,
      customerName: "River City Bakery",
      generalDescr: '4" x 4" seasonal muffin topper',
      press: "5.1",
      priority: "Open",
      quantity: 68000,
      footage: 7400,
      pressTime: 2.2,
      stock: "854",
      shipByDate: friday,
      dueOnSiteDate: friday,
      custPoNum: "PO-665830",
      mainTool: "854",
      toolNo2: "D-221",
    }),
  ];

  const assignments = [
    {
      id: "asg-demo-21041",
      jobId: "21041",
      dayKey: isoDate(monday),
      press: "5.1",
      kind: "press",
      status: "scheduled",
      createdAt: atTime(monday, 7, 30),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 0,
      shipDate: "",
    },
    {
      id: "asg-demo-21050",
      jobId: "21050",
      dayKey: isoDate(monday),
      press: "5.1",
      kind: "press",
      status: "scheduled",
      createdAt: atTime(monday, 8, 0),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 1,
      shipDate: "",
    },
    {
      id: "asg-demo-21042",
      jobId: "21042",
      dayKey: isoDate(tuesday),
      press: "6.1",
      kind: "press",
      status: "scheduled",
      createdAt: atTime(tuesday, 7, 45),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 0,
      shipDate: "",
    },
    {
      id: "asg-demo-21043",
      jobId: "21043",
      dayKey: isoDate(wednesday),
      press: "1.1",
      kind: "press",
      status: "scheduled",
      createdAt: atTime(wednesday, 7, 50),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 0,
      shipDate: "",
    },
    {
      id: "asg-demo-21044",
      jobId: "21044",
      dayKey: isoDate(thursday),
      press: "2.1",
      kind: "press",
      status: "scheduled",
      createdAt: atTime(thursday, 7, 40),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 0,
      shipDate: "",
    },
    {
      id: "asg-demo-21045",
      jobId: "21045",
      dayKey: isoDate(thursday),
      press: "8",
      kind: "press",
      status: "scheduled",
      createdAt: atTime(thursday, 9, 0),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 0,
      shipDate: "",
    },
    {
      id: "asg-demo-manual-maintenance",
      jobId: "",
      dayKey: isoDate(friday),
      press: "6.1",
      kind: "manual",
      manualTitle: "Preventive Maintenance",
      status: "scheduled",
      createdAt: atTime(friday, 6, 30),
      finishedAt: null,
      finishedBy: "",
      laneOrder: 0,
      shipDate: "",
    },
    {
      id: "asg-demo-21046",
      jobId: "21046",
      dayKey: isoDate(thursday),
      press: "5.1",
      kind: "press",
      status: "finished",
      createdAt: atTime(thursday, 6, 45),
      finishedAt: atTime(thursday, 10, 25),
      finishedBy: "Shipping",
      laneOrder: 0,
      shipDate: todayKey,
    },
    {
      id: "asg-demo-21047",
      jobId: "21047",
      dayKey: isoDate(thursday),
      press: "6.1",
      kind: "press",
      status: "finished",
      createdAt: atTime(thursday, 7, 10),
      finishedAt: atTime(thursday, 11, 10),
      finishedBy: "Admin",
      laneOrder: 1,
      shipDate: todayKey,
    },
    {
      id: "asg-demo-21048",
      jobId: "21048",
      dayKey: isoDate(friday),
      press: "8",
      kind: "finish-only",
      status: "finished",
      createdAt: atTime(friday, 8, 15),
      finishedAt: atTime(friday, 9, 5),
      finishedBy: "Shipping",
      laneOrder: null,
      shipDate: isoDate(friday),
    },
  ];

  const users = [
    {
      id: "demo-admin",
      username: "Admin",
      password: DEMO_DEFAULT_PASSWORD,
      role: "Management",
      accessMode: "edit",
      tabs: [...BASE_TABS, "User Admin"],
      canManageUsers: true,
      isAdmin: true,
      createdAt: atTime(monday, 6, 0),
      createdBy: "system",
    },
    {
      id: "demo-shipping",
      username: "Shipping",
      password: DEMO_DEFAULT_PASSWORD,
      role: "Warehouse/Shipper",
      accessMode: "edit",
      tabs: BASE_TABS.filter((tab) => !["New Request", "Open Requests"].includes(tab)),
      canManageUsers: false,
      isAdmin: false,
      createdAt: atTime(monday, 6, 5),
      createdBy: "Admin",
    },
    {
      id: "demo-operator",
      username: "Operator",
      password: DEMO_DEFAULT_PASSWORD,
      role: "Operator",
      accessMode: "view",
      tabs: ["Scheduler"],
      canManageUsers: false,
      isAdmin: false,
      createdAt: atTime(monday, 6, 10),
      createdBy: "Admin",
    },
  ];

  return {
    jobs,
    assignments,
    pressOperators: {
      [`${isoDate(monday)}::5.1`]: "M. Lopez",
      [`${isoDate(tuesday)}::6.1`]: "J. Harper",
      [`${isoDate(wednesday)}::1.1`]: "D. Kim",
      [`${isoDate(thursday)}::2.1`]: "S. Patel",
      [`${isoDate(thursday)}::8`]: "T. Morgan",
    },
    pressDuties: {
      [`${isoDate(monday)}::5.1`]: "Breakfast labels",
      [`${isoDate(tuesday)}::6.1`]: "Release backlog",
      [`${isoDate(friday)}::6.1`]: "Maintenance",
      [`${isoDate(thursday)}::8`]: "Digital reruns",
    },
    requests: [
      {
        id: "req-demo-1",
        jobNumber: "21044",
        customer: "Harbor Snacks",
        requestorName: "Packaging Team",
        description: "Confirm the revised copy block before releasing this ticket to press.",
        requestType: "Ticket Checklist",
        assignedToAccount: "Admin",
        attachments: [],
        createdAt: atTime(wednesday, 14, 0),
        createdByAccount: "Shipping",
        completedAt: null,
        completedByAccount: "",
        status: "open",
      },
      {
        id: "req-demo-2",
        jobNumber: "21045",
        customer: "Grove & Grain",
        requestorName: "Customer Service",
        description: "Please confirm digital proofs and carton count before the afternoon pickup.",
        requestType: "General Request",
        assignedToAccount: "Shipping",
        attachments: [],
        createdAt: atTime(thursday, 9, 15),
        createdByAccount: "Admin",
        completedAt: null,
        completedByAccount: "",
        status: "open",
      },
      {
        id: "req-demo-3",
        jobNumber: "21032",
        customer: "Valley Fresh",
        requestorName: "Sales Support",
        description: "Added pallet label note and approved the carton quantity update.",
        requestType: "General Request",
        assignedToAccount: "",
        attachments: [],
        createdAt: atTime(tuesday, 10, 20),
        createdByAccount: "Admin",
        completedAt: atTime(tuesday, 13, 5),
        completedByAccount: "Shipping",
        status: "done",
      },
    ],
    pullPaperRequests: [
      {
        id: "paper-demo-1",
        details: 'Stock 266 Width 9.5" 1 roll to Press 5.1',
        target: "Press 5.1",
        status: "open",
        createdAt: atTime(thursday, 8, 5),
        createdBy: "Operator",
        completedAt: null,
        completedBy: "",
      },
      {
        id: "paper-demo-2",
        details: 'Stock 585 Width 13" 2 rolls to Press 6.1',
        target: "Press 6.1",
        status: "done",
        createdAt: atTime(wednesday, 7, 20),
        createdBy: "Operator",
        completedAt: atTime(wednesday, 8, 0),
        completedBy: "Shipping",
      },
    ],
    notes: [
      {
        id: "note-demo-1",
        ownerUsername: "Admin",
        text: "Walk leadership through the weekly board, shipping workflow, and Excel export.",
        completed: false,
        createdAt: atTime(thursday, 7, 0),
        completedAt: "",
      },
      {
        id: "note-demo-2",
        ownerUsername: "Admin",
        text: "Mention that the demo workspace uses fake customers and fake PO numbers only.",
        completed: false,
        createdAt: atTime(thursday, 7, 5),
        completedAt: "",
      },
    ],
    registrationRequests: [],
    suppliesRequests: [
      {
        id: "supply-demo-1",
        details: "Order more black thermal ribbons for the shipping station printers.",
        status: "open",
        attachments: [],
        createdAt: atTime(thursday, 8, 40),
        createdBy: "Shipping",
        completedAt: null,
        completedBy: "",
      },
    ],
    shipmentGroups: [
      {
        id: "ship-demo-1",
        label: "Cedar / Maple release skid",
        method: "JP Express",
        packageCount: 2,
        packageType: "Skids",
        totalCost: 196.5,
        billAmount: 410,
        notes: "Demo shipment group with two completed release jobs.",
        shipDate: todayKey,
        createdAt: atTime(now, 12, 10),
        createdBy: "Shipping",
        attachments: [],
        jobItems: [
          {
            id: "21046",
            number: "21046",
            customerName: "Cedar Valley Coffee",
            generalDescr: '3" x 5.25" Espresso roast release',
            press: "5.1",
            ticQuantity: 88000,
            shipByDate: thursday.toISOString(),
            finishedAt: atTime(thursday, 10, 25),
            finishedBy: "Shipping",
          },
          {
            id: "21047",
            number: "21047",
            customerName: "Maple Street Tea",
            generalDescr: '4.125" x 3.125" Variety pack panel',
            press: "6.1",
            ticQuantity: 134000,
            shipByDate: thursday.toISOString(),
            finishedAt: atTime(thursday, 11, 10),
            finishedBy: "Admin",
          },
        ],
      },
    ],
    shipmentEmailLogs: [
      {
        id: "email-log-demo-1",
        shipDate: todayKey,
        recipients: "demo-warehouse@example.com",
        cc: "demo-leadership@example.com",
        subject: `Daily shipments for ${todayKey}`,
        body: "Demo shipment summary sent from the sample workspace.",
        jobCount: 2,
        totalCost: 196.5,
        totalBill: 410,
        methods: ["JP Express"],
        createdAt: atTime(now, 12, 30),
        createdBy: "Shipping",
      },
    ],
    shipmentEmailGroups: [
      {
        id: "email-group-demo-1",
        name: "Demo distro",
        recipients: "demo-warehouse@example.com",
        cc: "demo-leadership@example.com",
      },
    ],
    activityLog: [
      {
        id: "activity-demo-1",
        actor: "Admin",
        action: "Loaded demo workspace",
        scope: "Users",
        description: "The sample workspace was opened for a company walkthrough.",
        createdAt: atTime(now, 8, 0),
        details: {},
      },
      {
        id: "activity-demo-2",
        actor: "Shipping",
        action: "Created shipment group",
        scope: "Shipping",
        description: "Cedar / Maple release skid was grouped for the demo ship date.",
        createdAt: atTime(now, 12, 10),
        details: { shipDate: todayKey, method: "JP Express" },
      },
      {
        id: "activity-demo-3",
        actor: "Operator",
        action: "Updated press duty",
        scope: "Scheduler",
        description: "Press 6.1 on Friday was marked for preventive maintenance.",
        createdAt: atTime(friday, 6, 30),
        details: { press: "6.1", dayKey: isoDate(friday) },
      },
    ],
    shipmentMethods: ["Skid", "FedEx", "UPS", "LTL", "Customer Pickup", "JP Express"],
    users,
    weekStart: weekStart.toISOString(),
  };
}
